### ISSUE TITLE
add Meilisearch

### ISSUE THREAD

**Issue by mafreud** [mafreud/millennium#31]
## TODO
- [x] deploy to DO
- [x] upload stock data
- [x] read data from Flutter
- [ ] add service class
